"use client";

import React, { useState } from "react";
import styles from "./page.module.css";
import HomeNavBar from "@/components/HomeNavBar/HomeNavBar";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { validateLoginForm } from "@/utils/validateLogin";
import { loginUser } from "@/api/authApi";
import { useTranslation } from "react-i18next";

export default function page() {
  const { t } = useTranslation();
  const router = useRouter();

  const [formData, setFormData] = useState({
    email: '',
    password: '',
    rememberMe: false
  });

  const [errors, setErrors] = useState({});

  /**
   * Controlled component function handleChange() that updates the state based on user input.
   * This is so the react component can track the value of the input field and update it when the user types.
   * (e) is the event generated by the user typing. we destructure for flexibility and readability and this allows
   * the function to handle different input types (text, checkbox, etc.) dynamically.
   */
  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;

    /**
     * ... is the spread operator and is the quickest way of copying an existing object into another one
     * prev is the previous state
     * [name] is the key of the object
     * type === "checkbox" ? checked : value is the value of the object
     */
    setFormData((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value
    }));
  };

  /**
   * Function to handle form submission, prior to submitting the data to the endpoint, we perform
   * client sided validation of the user input through using the validateLoginForm (found in utils).
   * If there are any errors present it gets returned in an object, and we then update the state
   * of the erros object in this component. If there are no errors all information is accurate and correct
   * and we can perform the post request to the backend. If authentication is successful, we route
   * the user to the dashboard page.
   * @param {*} e - The event generated by the user submitting the form
   * @returns - Nothing, just handles the form submission
   */
  const submitForm = async (e) => {
    //prevents browser from refreshing the page
    e.preventDefault();

    const validationErrors = validateLoginForm(formData, t);
    setErrors(validationErrors);

    if (Object.keys(validationErrors).length > 0) {
      return;
    }

    try {
      await loginUser({email: formData.email, password: formData.password, rememberMe: formData.rememberMe})
      alert("Logged in successfully!");
      router.push("/dashboard");
    } catch (error) {
      alert("Error: " + error);
    }

  };

  return (
    <div className={styles.wrapper}>
      <HomeNavBar showLinks={false}/>

      <main className={styles.main}>

        <section className={styles.card}>

          <div className={styles.header}>
            <h1>{t("login.title")}</h1>
            <p>{t("login.subtitle")}</p>
          </div>

          <form name="login-form" className={styles.loginForm} onSubmit={submitForm} autoComplete="off">
            <label htmlFor="email">{t("login.email")}
              <input type="email" id="email" name="email" required placeholder={t("login.emailexample")} value={formData.email} onChange={handleChange} />
              {errors.email && <span className={styles.error}>{errors.email}</span>}
            </label>

            <label htmlFor="password">{t("login.password")}
              <input type="password" id="password" name="password" required placeholder={t("login.passwordExample")} value={formData.password} onChange={handleChange}/>
              {errors.password && <span className={styles.error}>{errors.password}</span>}
            </label>

            <div className={styles.optionsRow}>
              <label className={styles.rememberMe}>
                <input type="checkbox" name="rememberMe" checked={formData.rememberMe} onChange={handleChange}/>
                {t("login.rememberme")}
              </label>

              <Link href="/forgot-password" className={styles.forgotPassword}>
                {t("login.forgotpassword")}
              </Link>
            </div>

            <button type="submit" className={styles.submitForm}>
              {t("login.continue")}
            </button>

            <p className={styles.goToSignUp}>
              {t("login.donthaveanaccount")}{" "}
              <Link href="/signup">{t("login.signup")}</Link>
            </p>
          </form>

        </section>

      </main>
      
    </div>
  );
}